version: 1.13.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
build_script:
- cmd: cmake -S . -B build -T v100
- cmake --build build --config Release -j --target package
artifacts:
- path: 'build/*.zip'
deploy:
  provider: GitHub
  auth_token:
    secure: XzGnVTRjZI2AuQzR5A6qPgZViAAbBVq7/VhM7O8kyTmjIkvUjH1RrwWiFLuinsus
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true

